global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['business-service:8082', 'user-service:8081', 'notification-service:8083', 'gateway-service:8080', 'service-discovery:8761']