metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s  # Aumentar período para economizar recursos

- module: system
  metricsets:
    - cpu
    - memory
    - network
  period: 60s  # Aumentar período

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_stderr: true