server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            time: time
            container_name: attrs.container_name
            image_name: attrs.image_name

      - timestamp:
          format: RFC3339Nano
          source: time

      - labels:
          container_name:
          image_name:

      - output:
          source: output