server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# Configurações básicas para 8.11.0
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "clinicboard-encryption-key-32-chars"

# Configurações de logging simplificadas
logging.root.level: info